# Generated by Django 2.1.7 on 2019-10-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Castomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=30)),
                ('type_of_insurance', models.CharField(max_length=30)),
                ('ending_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(to='Appeal.Service'),
        ),
        migrations.AddField(
            model_name='castomers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appeal.Company'),
        ),
    ]
