# Generated by Django 2.1.7 on 2019-10-26 13:48

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Appeal', '0003_auto_20191026_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Castomers',
        ),
    ]
