# Generated by Django 2.1.7 on 2019-10-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('Appeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='services',
        ),
        migrations.AddField(
            model_name='castomers',
            name='number',
            field=models.CharField(default='84951234567', max_length=12),
        ),
        migrations.AddField(
            model_name='castomers',
            name='services',
            field=models.ManyToManyField(default=None, to='Appeal.Service'),
        ),
        migrations.AlterField(
            model_name='castomers',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
