# Generated by Django 2.1.7 on 2019-10-26 13:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Appeal', '0002_auto_20191025_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Castomers',
            new_name='Customers',
        ),
    ]
