# Generated by Django 2.1.7 on 2019-10-26 14:04

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Appeal', '0004_auto_20191026_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Castomers',
            new_name='Customers',
        ),
    ]
